// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Project Rovo",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Project Rovo",
            targets: ["AppModule"],
            bundleIdentifier: "com.mcrich.Project-Ravo",
            teamIdentifier: "L7JQRVXU2V",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .leaf),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Project Ravo would like to use your microphone."),
                .speechRecognition(purposeString: "Project Ravo would like to use speech recognition software."),
                .camera(purposeString: "Project Ravo would like to use your camera."),
                .photoLibrary(purposeString: "Project Ravo would like to use your photo library.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)