// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Teddy",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Teddy",
            targets: ["AppModule"],
            bundleIdentifier: "com.mcrich.Project-Rovo",
            teamIdentifier: "L7JQRVXU2V",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Project Rovo would like to use your microphone."),
                .speechRecognition(purposeString: "Project Rovo would like to use speech recognition software."),
                .camera(purposeString: "Project Rovo would like to use your camera."),
                .photoLibrary(purposeString: "Project Rovo would like to use your photo library."),
                .fileAccess(.pictureFolder, mode: .readWrite),
                .locationWhenInUse(purposeString: "Project Rovo would like to use your location when the app is active.")
            ],
            appCategory: .photography,
            additionalInfoPlistContentFilePath: "Info.plist"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageModes: [.version("6")]
)
